# 项目相关配置
eric4j:
  # 名称
  name: Eric4j
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/uploadPath，Linux配置 /home/uploadPath）
  profile: uploadPath
  # 获取ip地址开关
  addressEnabled: false
  enableScheduleTaskIps: 122.9.85.114 #启用定时任务的公网IP列表，多地址时用英文逗号分隔
  gaodeIp: https://demo.matetrip.cn/dist/gaodeditu/index.html#/
  # webSocket地址，即服务所在IP，https的端口用wss打头；http用ws打头
  webSocketUrl: wss://122.9.85.114:8011/imServer/
  # webSocketUrl: ws://10.88.27.246:8011/imServer/


# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8089
  # SSL详见application-druid.xml配置
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100



# Spring配置
spring:
  profiles:
    active: dev
  #数据库连接信息
  datasource:
    url: "jdbc:mysql://${const.sql.host}:${const.sql.port}/eric?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true"
    username: eric
    password: aA22431160.
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # 初始连接数
    initialSize: 5
    # 最小连接池数量
    minIdle: 10
    # 最大连接池数量
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置连接超时时间
    connectTimeout: 30000
    # 配置网络超时时间
    socketTimeout: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 600
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000
    # 配置检测连接是否有效
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    webStatFilter:
      enabled: true
    statViewServlet:
      enabled: true
      # 设置白名单，不填则允许所有访问
      allow:
      url-pattern: /druid/*
      # 控制台管理用户名和密码
      login-username: admin
      login-password: admin
    filter:
      stat:
        enabled: true
        # 慢SQL记录
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 100MB
      # 设置总上传的文件大小
      max-request-size: 200MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  redis:
    database: 1   #redis的0号数据库
    host: 106.14.58.169
    port: 6379
    password: 123456
#    timeout: 600000 #连接超时时间600毫秒
#    lettuce:
#      pool:
#        max-active: 60 #连接池最大连接数
#        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
#        min-idle: 1 #连接池中的最小空闲连接
#        max-idle: 8 #连接池中的最大空闲连接
  mvc:
    converters:
      preferred-json-mapper:fastjson


# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.eric.*
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*.xml
  #  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml


# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /user/login/username
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关 TODO-2023
    captchaEnabled: false
    # 验证码类型 math 数字计算 char 字符验证
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
    # 设置密钥，务必保持唯一性（生成方式，直接拷贝到main运行即可）Base64.encodeToString(CipherUtils.generateNewKey(128, "AES").getEncoded()) （默认启动生成随机秘钥，随机秘钥会导致之前客户端RememberMe Cookie无效，如设置固定秘钥RememberMe Cookie则有效）
    cipherKey:
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false
  rememberMe:
    # 是否开启记住我
    enabled: false
session:
  redis:
    inMemoryTimeout: 600 #session-Redis保存在内存中的超时时间(秒)，默认值 600
    saveToRedisInterval: 60 #往Redis保存session信息间隔(秒)，默认值 60，间隔太短会影响性能


jwt:
  # token过期时间
  accessTokenExpireTime: 86400000
  # 1000*60*60*24 24\u4E2A\u5C0F\u65F6
  refreshTokenExpireTime: 86400000
  issuer: StarPay
  secretKey: cdc4893a67fb48479763

pagehelper:
  reasonable: false #分页合理化参数，为 true 时，pageNum<=0 会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  supportMethodsArguments: true  # 是否支持通过Mapper接口参数来传递分页参数，为 true 时，分页插件会从查询方法的参数值中查找 pageNum、pageSize 参数的值进行自动分页。默认值 false.
  pageSizeZero: true #设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0, 就会查询出全部的结果(相当于没有执行分页查询，但是返回结果仍然是 Page 类型),默认值为 false，

