# 项目相关配置
eric4j:
  # 名称
  name: Eric4j
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/uploadPath，Linux配置 /home/uploadPath）
  profile: uploadPath
  # 获取ip地址开关
  addressEnabled: false
  enableScheduleTaskIps: 122.9.85.114 #启用定时任务的公网IP列表，多地址时用英文逗号分隔
  gaodeIp: https://demo.matetrip.cn/dist/gaodeditu/index.html#/
  # webSocket地址，即服务所在IP，https的端口用wss打头；http用ws打头
  webSocketUrl: wss://122.9.85.114:8011/imServer/
  # webSocketUrl: ws://10.88.27.246:8011/imServer/


# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8089
  # SSL详见application-druid.xml配置
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100



# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 100MB
      # 设置总上传的文件大小
      max-request-size: 200MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  redis:
    database: 0   #redis的0号数据库
    host: 106.14.58.169
    port: 6379
    password: 123456
    timeout: 60000 #连接超时时间600毫秒
    lettuce:
      pool:
        max-active: 60 #连接池最大连接数
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 1 #连接池中的最小空闲连接
        max-idle: 8 #连接池中的最大空闲连接



# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.eric.*
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*.xml
  #  mapperLocations: classpath*:mapper/**/*Mapper.xml

  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml


# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true



# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /user/login/username
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关 TODO-2023
    captchaEnabled: false
    # 验证码类型 math 数字计算 char 字符验证
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
    # 设置密钥，务必保持唯一性（生成方式，直接拷贝到main运行即可）Base64.encodeToString(CipherUtils.generateNewKey(128, "AES").getEncoded()) （默认启动生成随机秘钥，随机秘钥会导致之前客户端RememberMe Cookie无效，如设置固定秘钥RememberMe Cookie则有效）
    cipherKey:
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false
  rememberMe:
    # 是否开启记住我
    enabled: false
session:
  redis:
    inMemoryTimeout: 600 #session-Redis保存在内存中的超时时间(秒)，默认值 600
    saveToRedisInterval: 60 #往Redis保存session信息间隔(秒)，默认值 60，间隔太短会影响性能


jwt:
  accessTokenExpireTime: 60000
  # 1000*60*60*24 24\u4E2A\u5C0F\u65F6
  refreshTokenExpireTime: 86400000
  issuer: StarPay
  secretKey: cdc4893a67fb48479763

pagehelper:
  reasonable: true  # 是否进行分页合理化
  supportMethodsArguments: true  # 是否支持通过Mapper接口参数来传递分页参数

