# 项目相关配置
eric4j:
  # 名称
  name: Eric4j
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/uploadPath，Linux配置 /home/uploadPath）
  profile: uploadPath
  # 获取ip地址开关
  addressEnabled: false
  enableScheduleTaskIps: 122.9.85.114 #启用定时任务的公网IP列表，多地址时用英文逗号分隔
  gaodeIp: https://demo.matetrip.cn/dist/gaodeditu/index.html#/
  # webSocket地址，即服务所在IP，https的端口用wss打头；http用ws打头
  webSocketUrl: wss://122.9.85.114:8011/imServer/
  # webSocketUrl: ws://10.88.27.246:8011/imServer/


# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8089
  # SSL详见application-druid.xml配置
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100



# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 100MB
      # 设置总上传的文件大小
      max-request-size: 200MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  redis:
    database: 0   #redis的0号数据库
    host: 106.14.58.169
    port: 6379
    #    password: 123456
    timeout: 600 #连接超时时间600毫秒
    lettuce:
      pool:
        max-active: 60 #连接池最大连接数
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 1 #连接池中的最小空闲连接
        max-idle: 8 #连接池中的最大空闲连接



# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.eric.*
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*.xml
  #  mapperLocations: classpath*:mapper/**/*Mapper.xml

  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml


# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true


