# 开发环境

#端口号，内置对象
server:
  port: 8089

const:
  # 服务器地址
  cloud:
    host: localhost
    port: ${server.port}
    baseUrl: http://${const.cloud.host}:${const.cloud.port}
  # 数据库地址
  sql:
    host: 106.14.58.169
    port: 3306
    baseUrl: http://${const.sql.host}:${const.sql.port}
  # 对象存储地址
  cos:
    host: 100
    port: name:${my.name} age:${my.age}
    baseUrl: 航歌
  # 本机静态资源地址
  static_dir: /norman/oss/

spring:
  profiles:
    active:
      -dev
  #数据库连接信息
  datasource:
    url: "jdbc:mysql://${const.sql.host}:${const.sql.port}/chinasoft?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true"
    username: eric
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  # redis缓存数据库
  redis:
    host: 106.14.58.169
    port: 6379
    password: 123456
  servlet:
    multipart:
      max-file-size: 20MB #单个文件最大为20M
      max-request-size: 20MB #单次请求文件总数大小为20M


